<?php

namespace App\Core\Analytics;

/**
 * Analytics Context DTO
 * 
 * Contains automatically enriched data about the current request, user, and device.
 * Generated by the AnalyticsContextBuilder.
 */
class AnalyticsContext
{
    public function __construct(
        public readonly ?string $userId = null,
        public readonly ?string $sessionId = null,
        public readonly ?string $ipAddress = null,
        public readonly ?string $userAgent = null,
        public readonly ?string $locale = null,
        public readonly ?string $referrer = null,
        public readonly ?string $url = null,
        public readonly array   $utmParams = [],
        public readonly array   $device = [] // os, browser, type
    ) {}

    public function toArray(): array
    {
        return [
            'user_id'    => $this->userId,
            'session_id' => $this->sessionId,
            'ip_address' => $this->ipAddress,
            'user_agent' => $this->userAgent,
            'locale'     => $this->locale,
            'referrer'   => $this->referrer,
            'url'        => $this->url,
            'utm_params' => $this->utmParams,
            'device'     => $this->device,
        ];
    }
}
