name: CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run Code Style Check (Pint)
      run: vendor/bin/pint --test

    - name: Run Static Analysis (PHPStan)
      run: vendor/bin/phpstan analyse --error-format=github

    - name: Execute Tests
      run: php artisan test --parallel
